#!/usr/bin/python3
#case 0: No exception raised
try:
    print("try")
except:
    print("except")
finally:
    print("finally")
